title: 此间文字
email: private@localhost
description: >-
  私人归档，自我梳理。记录所见、所思、所读。
baseurl: ""
url: "https://bosszhipiao.github.io"

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
timezone: Asia/Shanghai

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: bosszhipiao
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .gitignore

paginate: 10
paginate_path: "/page:num/"
